# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Iso Calendar
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - public_repo
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: khoilr
          template: classic
          base: ""
          config_display: large
          config_timezone: Asia/Saigon
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          filename: "images/isocalendar.svg"
          extras_css: |
            h2.field {
              font-weight: bold; 
              font-size: 18px;
              color: #F9C859;
            }
            div.row {
              visibility: hidden;
            }
          extras_js: |
            document.querySelectorAll('[fill="#ebedf0"]')?.forEach(e => e.setAttribute("fill", "#22272e"))
            document.querySelectorAll('[fill="#9be9a8"]')?.forEach(e => e.setAttribute("fill", "#fca3be"))
            document.querySelectorAll('[fill="#40c463"]')?.forEach(e => e.setAttribute("fill", "#fa729b"))
            document.querySelectorAll('[fill="#30a14e"]')?.forEach(e => e.setAttribute("fill", "#f84079"))
            document.querySelectorAll('[fill="#216e39"]')?.forEach(e => e.setAttribute("fill", "#f60f56"))

          