# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Most Used Languages
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - public_repo
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: khoilr
          template: classic
          base: ""
          config_display: regular
          config_timezone: Asia/Saigon
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 1000
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_colors: jupyter notebook:#F9C859
          filename: "images/actions/most-languages.svg"
          extras_css: |
            h2.field{ 
              font-weight: bold;
              font-size: 18px;
              color: #F9C859;
            }
            h3 {
              color: #10B1FE;
            }
            :root {
              --color-calendar-graph-day-L1-bg: #fca3be;
              --color-calendar-graph-day-L2-bg: #fa729b;
              --color-calendar-graph-day-L3-bg: #f84079;
              --color-calendar-graph-day-L4-bg: #f60f56;
            }
            .entry { 
              color: #ABB2BF;
            }
            h2.field svg {
              display:none;
            }
            svg {
              background: #22272e;
            }
